POST http://localhost:5000/register HTTP/1.1
Content-Type: application/json

{
    "username": "panchami",
    "email": "panchami@gmail.com",
    "password": "panchami",
    "name": "panchami_apnacollege"
}

###

POST http://localhost:5000/login HTTP/1.1
Content-Type: application/json

{
    "emailOrUsername": "rahul",
    "password": "rahul"
}

###
GET http://localhost:5000/get_user_and_profile
Content-Type: application/json

{
    "token": ""
}

###

POST http://localhost:5000/update_profile_data HTTP/1.1  
Content-Type: application/json  

{
    "token": "",
    "bio": "",
    "currentPost": "",
    "pastWork": [
        {
            "company": "",
            "position": "",
            "years": ""
        },
        {
            "company": "",
            "position": "",
            "years": ""
        }
    ],
    "education": [
        {
            "school": "",
            "degree": "",
            "fieldOfStudy": "",
            "years": ""
        }
    ]
}

###
GET http://localhost:5000/user/get_all_users

###
GET http://localhost:5000/posts HTTP/1.1